name: 'File List'
description: 'lists all config files'
inputs:
  directory:
    description: 'directory to look through'
    required: false
    default: ''
  file_extension:
    description: 'file extension filter. (e.g., "txt","yml")'
    required: false
    default: ''
  only_files_starts_with:
    description: 'use only files which starts with. list is allowed (e.g., "prod_,dev")'
    required: false
    default: ''
  only_files_starts_with_delimiter:
    description: 'delimiter for the only files list (default: ",")'
    required: false
    default: ','
  ignore_files_starts_with:
    description: 'files start with are ignored. list is allowed (e.g., "ingore_,default")'
    required: false
    default: ''
  ignore_files_starts_with_delimiter:
    description: 'delimiter for the ingored files list (default: ",")'
    required: false
    default: ','
outputs:
  files: # output will be available to future steps
    description: 'All files as json list'
  file_names: # output will be available to future steps
    description: 'All file names without extension as json list'
runs:
  using: 'node12'
  main: 'dist/index.js'
